### ISSUE TITLE
Unexpected border coming over background color with the color chosen for animation.

### ISSUE THREAD

**Issue by ghost** [RobertFOConnor/react-native-progress-wheel#11]
I can see very light border of animation color on backgroundColor.

**Comment by RobertFOConnor** [comment]
Fixed in version 1.0.5.

**Comment by carloseustaquio** [comment]
Version 1.0.5, I still can see this light border there. Only happens when `fullColor` is set. @RobertFOConnor 
![image](https://user-images.githubusercontent.com/43277022/125971295-043acca3-ceab-4628-a07c-bb3359472697.png)
