### ISSUE TITLE
How can I render a child component?

### ISSUE THREAD

**Issue by FFFra** [RobertFOConnor/react-native-progress-wheel#13]
Im doing
```

<AnimatedProgressWheel
            ref={ref => (this.progressWheel = ref)}
            size={130}
            width={5}
            color={'yellow'}
            animateFromValue={0}
            backgroundColor={'orange'}>
            <View style={styles.captureBtnInternal} />
          </AnimatedProgressWheel>
```

but the inner view is not rendering.

Thank u so much!

**Comment by RobertFOConnor** [comment]
Hi there! For now, the AnimatedProgressWheel component does not accept children. If you want to render something within the circle, I would suggest using `position: 'absolute'` to overlay your view on top of the wheel. Let me know if this helps. 
Thanks for using my library. :)

**Comment by FFFra** [comment]
Hello! Thank u very much! I manage the problem positioning the elements.

Cheers!
