### ISSUE TITLE
Border-Radius for outer circle

### ISSUE THREAD

**Issue by michaelpomogajko** [RobertFOConnor/react-native-progress-wheel#15]
Hey, is it possible to make the progressing circle have border-radius?

Thanks

**Comment by RobertFOConnor** [comment]
Hi there! Unfortunately, this effect is not available out-of-the-box. You could achieve this effect by using 2 progress circles layered over each other (e.g. 1st with radius of 50, 2nd positioned on top with radius 45). The thickness of the 2nd wheel should be less than the one under it.

I hope this helps. If you need me to explain further please let me know so I can close this.

Thanks for using my library. :)
