### ISSUE TITLE
I think there is bug of positions each components

### ISSUE THREAD

**Issue by solidw** [RobertFOConnor/react-native-progress-wheel#21]
**Describe the bug**
I think there is bug of positions each components

**To Reproduce**
1. yarn add react-native-progress-wheel
2. Just write example code with some props

**Screenshots**
![image](https://user-images.githubusercontent.com/33471826/82825976-34482a00-9ee7-11ea-8c56-c03b5aa0c7b0.png)

**Desktop (please complete the following information):**
Android avd

**Additional context**
`package.json`
"react": "16.11.0",
"react-native": "0.62.2",
"react-native-progress-wheel": "^1.0.5",

Can you guess what the problem ?

**Comment by solidw** [comment]
I solved this problem when I type 
```
yarn remove react-native-progress-wheel
yarn add react-native-progress-wheel@1.0.4
```

I still don't know why the bug occured at 1.0.5 version but thank you for your package :)

**Comment by ochrostowska** [comment]
For me same thing happens both on 1.0.5 and downgraded 1.0.4 version :( On iOS animation is perfect, but Android gets crazy!

**Comment by SwaroopS94** [comment]
Same happens with me as well, but on particular devices.

**Comment by conny-nyman** [comment]
Same issue for me in both `v.1.0.5` and `v.1.0.4` _(and perhaps earlier versions as well)_, tested on Samsung S8 with Android 9.

**Comment by timothyerwin** [comment]
yeah the animations are smooth but the component is definitely glitchy. mine has lines showing up and slicing the circle. I'm using android.

...looking at the code I think it's the weird circle half stuff...just do a complete circle...why slice it up?

**Comment by RobertFOConnor** [comment]
The issue arises from the use of the containerColor prop. This should not be used.
