### ISSUE TITLE
Make the line cap rounded instead of flat

### ISSUE THREAD

**Issue by ShivamJoker** [RobertFOConnor/react-native-progress-wheel#42]
Thanks for the great work @RobertFOConnor 
It would be great if we could get rounded cap progress indicator like this:
![image](https://github.com/RobertFOConnor/react-native-progress-wheel/assets/23727670/1366d998-47cc-4a87-9601-2125d844ddf8)

Right now this is what it looks like:
![image](https://github.com/RobertFOConnor/react-native-progress-wheel/assets/23727670/2c4d9276-57ca-4ccc-8587-588d40295dfa)

**Comment by RobertFOConnor** [comment]
You can update to the latest version (v2.0.2) and use the rounded prop.

**Comment by ShivamJoker** [comment]
That was quick.
Thanks a lot for the new release.
