### ISSUE TITLE
Index Value

### ISSUE THREAD

**Issue by kvrscream** [RobertFOConnor/react-native-progress-wheel#6]
Hi. Does exist some exhibition a percent value?
Thanks

**Comment by RobertFOConnor** [comment]
@kvrscream I'm not sure I understand your question. If you want to set the percentage of progress simply use the progress prop. E.g. for 45% you can set progress={45}

**Comment by kvrscream** [comment]
Sorry i dont speak inglish kkk

I try say this: 
![1*030z292Oqiizj5L9pLVaow](https://user-images.githubusercontent.com/12921095/59165033-ae6f7b00-8aeb-11e9-97c3-4cd0918f290e.png)
